// Generates src/icons/glyphs.ts from the v1 framework's icon masks.
// Source of truth: ../src/css/icons/content.css (repo root). Regenerate with
// `node scripts/extract-icons.mjs` — never hand-edit the output.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "src", "css", "icons", "content.css");
const outFile = join(here, "..", "src", "icons", "glyphs.ts");

const css = readFileSync(source, "utf8");

// Glyph vars use both spellings: --icon_name (line icons) and --icon-name
// (content icons). Only entries carrying an SVG data URI are glyphs.
const glyphs = {};
for (const m of css.matchAll(/--icon[_-]([a-z0-9-]+):\s*url\("data:image\/svg\+xml,([^"]+)"\)/g)) {
  const [, name, encoded] = m;
  let svg = decodeURIComponent(encoded);
  // v1 hardcodes assorted ink colours; components want currentColor.
  // fill='none' must survive (stroke-based glyphs rely on it).
  svg = svg.replaceAll(/(stroke|fill)=(['"])(?!none)[^'"]*?\2/g, "$1=$2currentColor$2");
  glyphs[name] = svg;
}

// Per-glyph aspect ratio: v1 stores width as calc((W / H) * icon-height);
// content icons have no width var, so fall back to the viewBox ratio.
const ratios = {};
for (const m of css.matchAll(/--icon[_-]([a-z0-9-]+)-width:\s*calc\(\((\d+(?:\.\d+)?) \/ (\d+(?:\.\d+)?)\)/g)) {
  const [, name, w, h] = m;
  ratios[name] = Number(w) / Number(h);
}
for (const [name, svg] of Object.entries(glyphs)) {
  if (ratios[name] === undefined) {
    const vb = svg.match(/viewBox='0 0 (\d+(?:\.\d+)?) (\d+(?:\.\d+)?)'/);
    if (vb) ratios[name] = Number(vb[1]) / Number(vb[2]);
  }
}

const names = Object.keys(glyphs);
const entries = names
  .map((n) => `  "${n}": { ratio: ${(ratios[n] ?? 1).toFixed(4)}, svg: ${JSON.stringify(glyphs[n])} },`)
  .join("\n");

const out = `// GENERATED by scripts/extract-icons.mjs from the v1 icon masks
// (src/css/icons/content.css at the repo root). Do not hand-edit — regenerate.
// Colours are rewritten to currentColor; most glyphs are stroke-based, so the
// Icon component's Weight prop can override stroke-width via CSS.

export type GlyphName = keyof typeof GLYPHS;

export const GLYPHS = {
${entries}
} as const;

export const GLYPH_NAMES = Object.keys(GLYPHS) as GlyphName[];
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(`Wrote ${names.length} glyphs to ${outFile}`);
const strokeless = names.filter((n) => !glyphs[n].includes("stroke="));
if (strokeless.length) console.log(`Fill-only (Weight has no effect): ${strokeless.join(", ")}`);
